version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 28018:27017
    volumes:
      - .dev/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: Endless2-Drift-Turf

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: Endless2-Drift-Turf
      ME_CONFIG_MONGODB_URL: mongodb://dev:Endless2-Drift-Turf@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  2024-sis-team8:
    image: 2024-sis-team8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://dev:Endless2-Drift-Turf@mongo:28018
      MONGODB_DB: 2024-sis-team8\
